# Generated by Django 5.2.3 on 2025-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('ticket_count', models.CharField(max_length=5)),
                ('total_amount', models.CharField(max_length=10)),
                ('invoice_nr', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('has_payed', models.CharField(max_length=1)),
            ],
        ),
    ]
