# Generated by Django 5.2.3 on 2025-06-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
