# Generated by Django 5.2.3 on 2025-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0002_rename_tickets_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Prijs van één ticket',
            },
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Ticket aanvragen'},
        ),
    ]
