# Generated by Django 5.2.3 on 2025-06-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0003_ticketprice_alter_ticket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('total_amount', models.CharField(max_length=10)),
                ('has_entered', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Kassa registraties',
            },
        ),
    ]
