# Generated by Django 5.2.3 on 2025-06-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0004_cashout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashout',
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
